name: 'Kubernetes toolset'
description: 'Github Action with Kubernetes tools: kubectl, helm, jq, awscli, doctl'
author: 'Stefan Prodan'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  command:
    description: 'command to run'
    required: true
  kubectl:
    description: 'kubectl version'
    required: false
  helm:
    description: 'helm version'
    required: false
  awscli:
    description: 'awscli version'
    required: false
  doctl:
    description: 'doctl version'
    required: false
runs:
  using: 'docker'
  image: 'docker://906062568112.dkr.ecr.us-east-2.amazonaws.com/kube-tools:v1'
  args:
    - ${{ inputs.command }}
    - ${{ inputs.kubectl }}
    - ${{ inputs.helm }}
    - ${{ inputs.awscli }}
    - ${{ inputs.doctl }}
